### ISSUE TITLE
how to change frequency ranges

### ISSUE THREAD

**Issue by jmika784** [physiozoo/physiozoo#20]
I was using your software for mice HRV data analyses. We want to change frequency ranges to LF: 0.15-0.60 Hz and HF: 2.5-5 Hz. However, the software won't allow me to do this change. How can we make this happen? Can you help me with this, please? Thanks

**Comment by goldina** [comment]
You can change the frequency, but max(LF) must be equal to min(HF).

**Comment by goldina** [comment]
You can do it in Options - Frequency Tab (see picture below):
![FR](https://user-images.githubusercontent.com/22255865/96365128-0e961880-1147-11eb-820c-8bd9e8cde40d.png)

**Comment by jmika784** [comment]
Thanks for the answer. I know where I could change the frequency ranges but Can you explain why Lfmax must be equally to HFmin? It would be pretty helpful for me to explain it to others as they expect me to do the analyses using LF: 0.15-0.60; HF: 2.5-5 Hz

**Comment by jbehar** [comment]
It is like this because the bands setting reflect the original definition of HRV spectral bands which are divided in three consecutive VLF, LF and HF bands. If you want to perform your experiment with the setting of two bands 0.15-0.60 and 2.5-5 Hz then you may virtually set VLF: 0.15-0.60; LF: 0.60-2.5Hz and HF: 2.5-5 and just ignore the "LF" band.
